"""Source-bound blackboard stickers; typography is rendered, not generated by AI.

Render with Pillow and fontTools. Export uses python-pptx and ReportLab lazily, so
the two commands may use different existing document runtimes. No font install,
network access, overwrite, user-source mutation or archive creation is performed.
"""
from pathlib import Path
import argparse
import hashlib
import html
import json
import math
import os
import re
from PIL import Image, ImageDraw, ImageFont, ImageChops, ImageFilter

PACKAGE=Path(__file__).resolve().parents[2]/'assets/blackboard'
COLORS={'pink':'#EB7CA8','blue':'#43BCE5','yellow':'#F3CF51',
        'mint':'#B8E5D5','coral':'#F19A88','lavender':'#D8CEF4'}
INK='#15212B'
FONTS={}


def digest(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_json(path,data):
    Path(path).write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')


def load_json(path):return json.loads(Path(path).read_text(encoding='utf-8-sig'))


def safe_name(text):
    if not text or text in ('.','..') or re.search(r'[<>:"/\\|?*\x00-\x1f]',text) or text[-1] in ' .':
        raise ValueError('Unsafe output name: '+repr(text))
    return text


def resolve_path(base,name):
    path=Path(name)
    return path.resolve() if path.is_absolute() else (base/path).resolve()


def resolve_fonts(spec,base,roles):
    system=Path(os.environ.get('WINDIR','C:/Windows'))/'Fonts'
    defaults={'display':PACKAGE/'fonts/KNMaiyuan-Regular.ttf',
              'explanation':PACKAGE/'fonts/LXGWZhenKaiGB-Regular.ttf',
              'title':PACKAGE/'fonts/ZCOOLKuaiLe-Regular.ttf',
              'reading':system/'msyhbd.ttc','math':system/'arial.ttf','unit':system/'msyh.ttc'}
    for role,path in spec.get('fonts',{}).items():
        if role not in defaults:raise ValueError('Unknown font role: '+role)
        defaults[role]=resolve_path(base,path)
    for role in roles:
        if role not in defaults or not defaults[role].is_file():
            raise ValueError('Missing font/字体 for '+role+'; provide an existing font file in spec.fonts. No silent fallback.')
    # Bundled files have fixed versions. Explicit overrides are separately fingerprinted.
    for row in load_json(PACKAGE/'font-sources.json'):
        path=PACKAGE/row['file']
        if path in [defaults[r] for r in roles] and digest(path)!=row['sha256']:
            raise ValueError('Bundled font hash mismatch: '+str(path))
    return {role:defaults[role] for role in roles}


def glyph_coverage(path,text):
    from fontTools.ttLib import TTFont
    font=TTFont(str(path),fontNumber=0)
    cmap=font.getBestCmap();font.close()
    missing=sorted({c for c in text if not c.isspace() and ord(c) not in cmap})
    if missing:raise ValueError('Missing font glyphs/缺字: '+''.join(missing))


def pill(text,font_path,color='pink',oval=False,size=210):
    ft=ImageFont.truetype(str(font_path),round(size));box=ft.getbbox(text,stroke_width=2)
    tw,th=box[2]-box[0],box[3]-box[1]
    ink=Image.new('L',(tw,th))
    ImageDraw.Draw(ink).text((-box[0],-box[1]),text,font=ft,fill=255,stroke_width=2,stroke_fill=255)
    if oval:
        w,h=math.ceil(tw*1.42+size*.12),math.ceil(th*1.64+size*.12)
        if len(text)==1:w=h=max(w,h)
    else:w,h=math.ceil(tw+size*.76),math.ceil(th+size*.56)
    pad=32
    for attempt in range(40):
        glyph=Image.new('L',(w+pad*2,h+pad*2));glyph.paste(ink,(pad+round((w-tw)/2),pad+round((h-th)/2)))
        margin=max(14,round(h*.08));safe=Image.new('L',glyph.size);sd=ImageDraw.Draw(safe)
        rect=(pad+margin,pad+margin,pad+w-margin,pad+h-margin)
        if oval:sd.ellipse(rect,fill=255)
        else:sd.rounded_rectangle(rect,radius=max(1,round(h*.40)-margin),fill=255)
        outside=ImageChops.subtract(glyph,safe)
        if outside.getbbox() is None:break
        w+=8;h+=6
    else:raise ValueError('Glyph cannot fit label safely: '+text)
    canvas=Image.new('RGBA',glyph.size);d=ImageDraw.Draw(canvas);rect=(pad,pad,pad+w,pad+h)
    if oval:d.ellipse(rect,fill=COLORS[color],outline='white',width=8)
    else:d.rounded_rectangle(rect,radius=round(h*.40),fill=COLORS[color],outline='white',width=8)
    canvas.alpha_composite(Image.composite(Image.new('RGBA',canvas.size,INK),Image.new('RGBA',canvas.size),glyph))
    meta={'safe_inset':margin,'outside_safe_pixels':0,'glyph_pixels':sum(glyph.histogram()[1:]),
          'text_height_fraction':th/h,'growth_steps':attempt,'shape':'ellipse' if oval else 'capsule'}
    return canvas,meta,{'glyph':glyph,'safe':safe}


def font(key, size):
    return ImageFont.truetype(str(FONTS[key]), round(size))

def paste_color(canvas, mask, color):
    canvas.alpha_composite(Image.composite(Image.new('RGBA', canvas.size, color),
                                         Image.new('RGBA', canvas.size), mask))

def fill_holes(mask):
    # Fill the backing, not the visible glyph: interior counters stay clean white.
    closed = mask.point(lambda p: 255 if p > 120 else 0)
    ImageDraw.floodfill(closed, (0, 0), 128)
    holes = closed.point(lambda p: 255 if p == 0 else 0).filter(ImageFilter.MaxFilter(5))
    return ImageChops.lighter(mask, holes)

def trim(im, pad=12):
    box = im.getchannel('A').getbbox()
    assert box is not None
    return ImageOps_expand(im.crop(box), pad)

def ImageOps_expand(im, pad):
    dest = Image.new('RGBA', (im.width + 2*pad, im.height + 2*pad))
    dest.alpha_composite(im, (pad, pad))
    return dest

def word(text, color='blue', title=False, size=240):
    ft = font('title' if title else 'brush', size)
    advance = [ft.getlength(c) for c in text]
    gap = -size * (0.035 if title else 0.025)
    width = math.ceil(sum(advance) + gap * max(0, len(text)-1))
    pad = round(size*.24)
    canvas_size = (width+pad*2, round(size*1.55))
    y = round(size*.12)
    def mask(stroke, solid=False):
        layer=Image.new('L', canvas_size)
        draw=ImageDraw.Draw(layer)
        x=pad
        for ch,step in zip(text,advance):
            draw.text((x,y),ch,font=ft,fill=255,stroke_width=round(stroke),stroke_fill=255)
            x += step+gap
        return fill_holes(layer) if solid else layer
    im=Image.new('RGBA',canvas_size)
    if title:
        for radius,fill,solid in [(size*.103,'#FFFDF7',True),(size*.09,COLORS['pink'],True),
                                  (size*.057,'#FFFFFF',True),(size*.018,INK,False),(0,'#FFDF58',False)]:
            paste_color(im,mask(radius,solid),fill)
    else:
        for radius,fill,solid in [(size*.108,'#FFFDF8',True),(size*.094,COLORS[color],True),
                                  (size*.058,'#FFFFFF',True),(size*.008,INK,False)]:
            paste_color(im,mask(radius,solid),fill)
    return trim(im,16)

def card(text, color='blue', unit='', size=190):
    ft=font('math',size);uf=font('sans',size*.48)
    # Keep the multiplication cross distinct from a handwritten letter x.
    display=text.replace('+','＋').replace('=','＝')
    # Arial fullwidth signs are absent on some installations; use its real math signs.
    display=text.replace('+',' + ').replace('=','   =   ' if '×' in text else ' = ').replace('×','   ×   ')
    box=ft.getbbox(display);tw=ft.getlength(display)
    ut=f'（{unit}）' if unit else ''
    uw=uf.getlength(ut) if ut else 0
    w=math.ceil(tw+uw+size*.46);h=math.ceil(size*1.32)
    im=Image.new('RGBA',(w+32,h+32));d=ImageDraw.Draw(im)
    d.rounded_rectangle((10,10,w+22,h+22),radius=20,fill=COLORS[color],outline='white',width=7)
    d.rounded_rectangle((34,34,w-2,h-2),radius=8,fill='#FFFDF7')
    y=(h-(box[3]-box[1]))/2-box[1]+16
    d.text((size*.23+16,y),display,font=ft,fill=INK)
    if ut:
        ub=uf.getbbox(ut)
        d.text((size*.23+16+tw,y+box[3]-ub[3]),ut,font=uf,fill=INK)
    crop=im.getchannel('A').getbbox()
    result=trim(im,16)
    start=size*.23+16-crop[0]+16
    tokens=[]
    for match in re.finditer(r'\d+|[×+=]',display):
        left=start+ft.getlength(display[:match.start()])
        right=start+ft.getlength(display[:match.end()])
        tokens.append({'text':match.group(),'center':(left+right)/2/result.width})
    lhs=display.split('=')[0].rstrip()
    result.info['anchors']={'tokens':tokens,'addends':[start/result.width,(start+ft.getlength(lhs))/result.width]}
    return result

def blank_card(width=1400,height=370,color='blue'):
    im=Image.new('RGBA',(width,height));d=ImageDraw.Draw(im)
    d.rounded_rectangle((16,16,width-16,height-16),radius=48,fill=COLORS[color],outline='white',width=9)
    d.rounded_rectangle((36,36,width-36,height-36),radius=30,fill='#FFFDF7')
    return im

def arrow():
    im=Image.new('RGBA',(1200,108));d=ImageDraw.Draw(im)
    d.line([(20,54),(1140,54)],fill='#FFFDF3',width=14)
    d.line([(1090,20),(1146,54),(1090,88)],fill='#FFFDF3',width=14,joint='curve')
    return im

def brace():
    # Two rounded corners with a visible center cusp; no sharp square stroke ends.
    im=Image.new('RGBA',(1400,120));d=ImageDraw.Draw(im)
    pts=[]
    curves=[((18,16),(18,72),(30,70),(76,70)),((76,70),(420,70),(640,70),(660,70)),
            ((660,70),(680,70),(692,85),(700,102)),((700,102),(708,85),(720,70),(740,70)),
            ((740,70),(960,70),(1270,70),(1324,70)),((1324,70),(1370,70),(1382,72),(1382,16))]
    for a,b,c,e in curves:
        for i in range(41):
            t=i/40;s=1-t
            pts.append((s**3*a[0]+3*s*s*t*b[0]+3*s*t*t*c[0]+t**3*e[0],s**3*a[1]+3*s*s*t*b[1]+3*s*t*t*c[1]+t**3*e[1]))
    d.line(pts,fill='#FFFDF3',width=12,joint='curve')
    return im

def dots(groups, count, different=None):
    counts=different or [count]*groups
    cell=160;maxn=max(counts);vertical=(len(counts)>=4)
    if vertical:
        w=len(counts)*cell+80;h=maxn*cell+80
    else:
        w=maxn*cell+80;h=len(counts)*cell+80
    scale=3
    im=Image.new('RGBA',(w*scale,h*scale));d=ImageDraw.Draw(im)
    for g,n in enumerate(counts):
        if vertical: box=(40+g*cell,32,40+(g+1)*cell-16,48+maxn*cell)
        else:box=(32,40+g*cell,48+n*cell,40+(g+1)*cell-16)
        d.rounded_rectangle(tuple(v*scale for v in box),radius=38*scale,fill='#FFFDF7',outline=COLORS['coral' if different else 'pink'],width=10*scale)
        for k in range(n):
            cx,cy=(40+g*cell+72,40+k*cell+72) if vertical else (40+k*cell+72,40+g*cell+72)
            d.ellipse(tuple(v*scale for v in (cx-36,cy-36,cx+36,cy+36)),fill='#43BCE5',outline='#166B91',width=5*scale)
    return trim(im,16*scale)


def preflight(spec,base):
    safe_name(spec['title'])
    if not spec.get('sources') or not spec.get('assets') or not spec.get('boards'):
        raise ValueError('sources, assets and boards are required')
    sources={}
    for row in spec['sources']:
        path=resolve_path(base,row['path'])
        if not path.is_file() or digest(path)!=row['sha256']:
            raise ValueError('Source hash mismatch/来源不一致: '+str(path))
        if row['id'] in sources:raise ValueError('Duplicate source ID')
        sources[row['id']]=row
    ids=set();roles=set();arithmetic=[]
    for a in spec['assets']:
        safe_name(a['name'])
        if not re.fullmatch(r'[a-zA-Z0-9_-]+',a['id']) or a['id'] in ids:raise ValueError('Invalid/duplicate asset ID')
        ids.add(a['id']);kind=a['kind']
        if kind not in ('word','pill','card','arrow','brace','dots','blank','image'):raise ValueError('Unknown kind: '+kind)
        allowed={'word':{'size'},'pill':{'size','oval'},'card':{'size','unit'},
                 'arrow':set(),'brace':set(),'dots':{'groups','count','different'},
                 'blank':{'width','height'},'image':{'source','sha256','padding'}}
        unknown=set(a.get('params',{}))-allowed[kind]
        if unknown:raise ValueError('Invalid params for '+kind+': '+', '.join(sorted(unknown))+'; color belongs on the asset, not params')
        if a.get('color','blue') not in COLORS:raise ValueError('Unknown palette color')
        if kind in ('word','pill','card') and not str(a.get('text','')).strip():raise ValueError('Empty text asset')
        if kind not in ('arrow','brace','blank'):
            if not a.get('source_refs') or not a.get('purpose'):raise ValueError('Content needs source_refs and teaching purpose: '+a['id'])
            for ref in a['source_refs']:
                src=sources.get(ref['source_id']);pages=ref.get('pages',[])
                if not src or not pages or any(not isinstance(p,int) or p<1 or p>src['page_count'] for p in pages):
                    raise ValueError('Invalid source page reference: '+a['id'])
        if kind in ('word','pill'):
            role=a.get('role')
            if role not in ('display','explanation','reading','title'):raise ValueError('Explicit semantic font role required')
            roles.add(role)
        if kind=='card':
            roles.update(('math','unit'))
            expr=re.sub(r'\s+','',a['text']).replace('＋','+').replace('＝','=')
            match=re.fullmatch(r'(\d+(?:[+×]\d+)*)=(\d+)',expr)
            if match:
                lhs,rhs=match.groups()
                if '+' in lhs and '×' in lhs:raise ValueError('Mixed arithmetic needs a reviewed custom image')
                values=[int(n) for n in re.split('[+×]',lhs)]
                result=math.prod(values) if '×' in lhs else sum(values)
                if result!=int(rhs):raise ValueError('Incorrect arithmetic/算式: '+expr)
                arithmetic.append({'id':a['id'],'expression':expr,'passed':True})
        if kind=='image':
            params=a['params'];path=resolve_path(base,params['source'])
            if not path.is_file() or digest(path)!=params['sha256']:raise ValueError('Image source hash mismatch')
    for b in spec['boards']:
        safe_name(b['name'])
        if not b.get('items') or any(i['id'] not in ids for i in b['items']):raise ValueError('Invalid board asset reference')
    fonts=resolve_fonts(spec,base,roles)
    for a in spec['assets']:
        if a['kind'] in ('word','pill'):glyph_coverage(fonts[a['role']],a['text'])
        elif a['kind']=='card':
            glyph_coverage(fonts['math'],a['text'])
            glyph_coverage(fonts['unit'],a.get('params',{}).get('unit',''))
    return fonts,arithmetic


def draw_boards(spec,assets,out):
    width,height=spec.get('size',[2000,1125]);background=spec.get('background','#294B42')
    boards=[];checks=[]
    if min(width,height)<200:raise ValueError('Board dimensions too small')
    for number,board in enumerate(spec['boards'],1):
        canvas=Image.new('RGBA',(width,height),background)
        ImageDraw.Draw(canvas).rounded_rectangle((22,22,width-22,height-22),radius=9,outline='#93B6A4',width=2)
        occupied=Image.new('L',(width,height));items=[];placed={}
        for entry in board['items']:
            key=entry['id'];a=assets[key];picture=Image.open(out/a['file']).convert('RGBA')
            if 'anchor' in entry:
                anchor=entry['anchor'];target=placed[anchor['target']]
                token=assets[target['id']]['anchors']['tokens'][anchor['token_index']]
                h=anchor['height'];w=picture.width/picture.height*h
                x=target['x']+target['w']*token['center']-w/2;y=target['y']+target['h']+anchor.get('gap_y',12)
            elif 'brace_for' in entry:
                target=placed[entry['brace_for']];start,end=assets[target['id']]['anchors']['addends']
                x=target['x']+target['w']*start-10;w=target['w']*(end-start)+20
                h=w*picture.height/picture.width;y=target['y']+target['h']+entry.get('gap_y',0)
            else:x,y,w,h=entry['box']
            if min(w,h)<=0:raise ValueError('Invalid item dimensions: '+key)
            scale=min(w/picture.width,h/picture.height);nw,nh=round(picture.width*scale),round(picture.height*scale)
            left,top=round(x+(w-nw)/2),round(y+(h-nh)/2)
            if min(left,top)<0 or left+nw>width or top+nh>height:raise ValueError('Board overflow: '+key)
            resized=picture.resize((nw,nh),Image.Resampling.LANCZOS)
            mask=resized.getchannel('A').point(lambda p:255 if p>220 else 0)
            overlap=ImageChops.multiply(occupied.crop((left,top,left+nw,top+nh)),mask)
            overlap_pixels=sum(overlap.histogram()[1:])
            if overlap_pixels>12 and not entry.get('intentional_overlap'):
                raise ValueError('Opaque sticker overlap: '+key+'; adjust placement, do not mark accidental collisions intentional')
            occupied.paste(ImageChops.lighter(occupied.crop((left,top,left+nw,top+nh)),mask),(left,top))
            canvas.alpha_composite(resized,(left,top))
            item={'id':key,'x':left,'y':top,'w':nw,'h':nh}
            if entry.get('intentional_overlap'):item['intentional_overlap']=entry['intentional_overlap']
            if a.get('label_fit'):
                glyph_height=a['label_fit']['text_height_fraction']*(a['height']-64)*scale
                if glyph_height<entry.get('minimum_label_px',22):raise ValueError('Label text too small at board size: '+key)
                checks.append({'board':number,'id':key,'visible_text_height_px':round(glyph_height,2),'safe_fit':True})
            items.append(item);placed[entry.get('instance_id',key)]=item
        filename=f'整板预览_{number}_{board["name"]}.png';canvas.convert('RGB').save(out/filename)
        boards.append({'name':board['name'],'notes':board.get('notes',''),'items':items,'preview':filename})
    return {'size':[width,height],'background':background,'boards':boards},checks


def render(spec_path,destination):
    spec_path=Path(spec_path).resolve();destination=Path(destination).resolve()
    if destination.exists():raise FileExistsError('Use a new version; output exists: '+str(destination))
    spec=load_json(spec_path);fonts,math_checks=preflight(spec,spec_path.parent)
    destination.mkdir(parents=True)
    (destination/'AGENTS.md').write_text('# Blackboard output\n\noutput/: Chinese-named PNG/PPTX/PDF/gallery. content.json and layout.json preserve actual source/font/layout data; manifest.json and checks.json record real artifacts and technical verification. Do not overwrite prior versions, install fonts, delete or publish. Static renders are not classroom hardware validation.\n',encoding='utf-8')
    out=destination/'output';out.mkdir();records=[]
    global FONTS
    FONTS={'title':fonts.get('title'),'math':fonts.get('math'),'sans':fonts.get('unit')}
    for number,source in enumerate(spec['assets'],1):
        a=dict(source);kind=a['kind'];params=a.get('params',{});color=a.get('color','blue');meta=None
        if kind=='word':
            FONTS['brush']=fonts[a['role']]
            image=word(a['text'],color=color,title=a['role']=='title',**params)
        elif kind=='pill':image,meta,_=pill(a['text'],fonts[a['role']],color=color,**params)
        elif kind=='card':image=card(a['text'],color=color,**params)
        elif kind=='arrow':image=arrow()
        elif kind=='brace':image=brace()
        elif kind=='dots':image=dots(**params)
        elif kind=='blank':image=blank_card(color=color,**params)
        elif kind=='image':
            image=Image.open(resolve_path(spec_path.parent,params['source'])).convert('RGBA')
            image=ImageOps_expand(image,params.get('padding',16))
        filename=f'{number:02d}_{a["name"]}.png';image.save(out/filename,dpi=(300,300))
        a.update(file=filename,width=image.width,height=image.height,anchors=image.info.get('anchors',{}),sha256=digest(out/filename))
        if meta:a['label_fit']=meta
        records.append(a)
    layout,label_checks=draw_boards(spec,{a['id']:a for a in records},out)
    font_records={role:{'path':str(path),'sha256':digest(path)} for role,path in fonts.items()}
    result={'title':spec['title'],'sources':spec['sources'],'spec':{'path':str(spec_path),'sha256':digest(spec_path)},
            'fonts':font_records,'assets':records,'layout':layout,'status':'rendered_not_visually_approved'}
    write_json(destination/'content.json',result);write_json(destination/'layout.json',layout)
    write_json(destination/'checks.json',{'render_passed':True,'arithmetic':math_checks,'label_sizes':label_checks,
               'labels':[{'id':a['id'],**a['label_fit']} for a in records if a.get('label_fit')],
               'visual_review':'pending; inspect actual PNGs and rendered PPT before final delivery'})
    write_json(destination/'manifest.json',{'rendered':True,'exported':False,'files':[{'file':p.name,'sha256':digest(p)} for p in out.iterdir()]})
    return result


def export(destination):
    from pptx import Presentation
    from pptx.util import Inches,Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_SHAPE
    from reportlab.pdfgen import canvas as pdfcanvas
    from reportlab.lib.utils import ImageReader
    destination=Path(destination).resolve();out=destination/'output'
    data=load_json(destination/'content.json');layout=data['layout'];assets={a['id']:a for a in data['assets']}
    if not load_json(destination/'checks.json')['render_passed']:raise ValueError('Render checks did not pass')
    for a in data['assets']:
        if digest(out/a['file'])!=a['sha256']:raise ValueError('Changed asset; create a new reviewed version: '+a['id'])
    title=data['title'];ppt_name=title+'_黑板贴可移动版.pptx';pdf_name=title+'_板书布局参考.pdf'
    if (out/ppt_name).exists() or (out/pdf_name).exists():raise FileExistsError('Do not overwrite exported files')
    width,height=layout['size'];prs=Presentation();prs.slide_width=Inches(width/100);prs.slide_height=Inches(height/100)
    pdf=pdfcanvas.Canvas(str(out/pdf_name),pagesize=(width*.72,height*.72));pdf.setTitle(title+'｜板书布局')
    for board in layout['boards']:
        slide=prs.slides.add_slide(prs.slide_layouts[6]);slide.background.fill.solid()
        slide.background.fill.fore_color.rgb=RGBColor.from_string(layout['background'].lstrip('#'))
        frame=slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Inches(.22),Inches(.22),Inches((width-44)/100),Inches((height-44)/100))
        frame.fill.background();frame.line.color.rgb=RGBColor.from_string('93B6A4');frame.line.width=Pt(1)
        frame.adjustments[0]=.01
        for item in board['items']:
            a=assets[item['id']];pic=slide.shapes.add_picture(str(out/a['file']),*[Inches(item[k]/100) for k in ('x','y','w','h')])
            pic.name=a['name'];pic._element.nvPicPr.cNvPr.set('descr',a.get('text') or a['name'])
        slide.notes_slide.notes_text_frame.text=board['notes']+'\n各贴纸为独立透明PNG对象，可移动、复制、缩放；文字不是原生可改字文本。'
        pdf.drawImage(ImageReader(str(out/board['preview'])),0,0,width=width*.72,height=height*.72);pdf.showPage()
    prs.save(out/ppt_name);pdf.save()
    guide=f'{title}｜黑板贴\n\n先打开素材总览.html。编号PNG为透明独立贴纸；PPT各贴纸可移动、缩放，但不是逐字可编辑文字。PDF是整板布局参考，不是按实际尺寸分页裁剪稿。按课堂进度逐步展示。\n\n采用已选择的字形角色和安全内边距；不需要安装字体。来源与教学用途见文字源清单。'
    (out/'使用说明.txt').write_text(guide,encoding='utf-8-sig')
    text='\n\n'.join(a['file']+'\n'+a.get('text','')+'\n用途：'+a.get('purpose','连接/底板')+'\n来源：'+json.dumps(a.get('source_refs',[]),ensure_ascii=False) for a in data['assets'])
    (out/'文字源清单.txt').write_text(text,encoding='utf-8-sig')
    e=html.escape
    boards=''.join(f'<figure><a href="{e(b["preview"])}"><img src="{e(b["preview"])}" alt="{e(b["name"])}"></a><figcaption>{e(b["name"])}</figcaption></figure>' for b in layout['boards'])
    tiles=''.join(f'<article><a href="{e(a["file"])}"><img src="{e(a["file"])}" alt="{e(a["name"])}"></a><p>{e(a["name"])}</p></article>' for a in data['assets'])
    page=f'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}｜黑板贴</title><style>*{{box-sizing:border-box}}body{{margin:0;background:#f4f2ea;color:#244e41;font:16px/1.7 "Microsoft YaHei",sans-serif}}main{{max-width:1400px;margin:auto;padding:28px}}img{{max-width:100%;height:auto}}figure{{margin:25px 0}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px}}article{{background:#294b42;color:white;padding:16px;border-radius:12px;min-width:0}}article a{{display:flex;height:150px;align-items:center;justify-content:center}}article img{{max-height:100%;object-fit:contain}}a{{color:#207a59}}@media(max-width:450px){{main{{padding:15px}}.grid{{grid-template-columns:1fr}}}}</style><main><h1>{e(title)}｜电子黑板贴</h1><p>{len(assets)}张独立透明素材 · {len(layout["boards"])}张整板</p><p><a href="{e(ppt_name)}">打开PPT</a> · <a href="{e(pdf_name)}">布局PDF</a> · <a href="使用说明.txt">使用说明</a></p>{boards}<h2>独立素材</h2><div class="grid">{tiles}</div></main></html>'
    (out/'素材总览.html').write_text(page,encoding='utf-8')
    manifest=load_json(destination/'manifest.json');manifest.update(exported=True,files=[{'file':p.name,'sha256':digest(p)} for p in sorted(out.iterdir())])
    write_json(destination/'manifest.json',manifest)
    return {'pptx':str(out/ppt_name),'pdf':str(out/pdf_name),'slides':len(layout['boards']),'pictures':sum(len(b['items']) for b in layout['boards'])}


def verify(destination):
    import zipfile
    import xml.etree.ElementTree as ET
    from pypdf import PdfReader
    destination=Path(destination).resolve();out=destination/'output';data=load_json(destination/'content.json')
    manifest=load_json(destination/'manifest.json');checks=[]
    for row in manifest['files']:checks.append((row['file'],digest(out/row['file'])==row['sha256']))
    spec_path=Path(data['spec']['path'])
    checks.append(('spec hash',digest(spec_path)==data['spec']['sha256']))
    for row in data['sources']:checks.append(('source '+row['id'],digest(resolve_path(spec_path.parent,row['path']))==row['sha256']))
    for a in data['assets']:
        im=Image.open(out/a['file']);checks.append(('alpha '+a['id'],im.mode=='RGBA' and im.getchannel('A').getextrema()==(0,255)))
    if not manifest['exported']:raise ValueError('Export is not complete')
    with zipfile.ZipFile(out/(data['title']+'_黑板贴可移动版.pptx')) as archive:
        ns={'p':'http://schemas.openxmlformats.org/presentationml/2006/main'}
        for i,b in enumerate(data['layout']['boards'],1):
            root=ET.fromstring(archive.read(f'ppt/slides/slide{i}.xml'))
            checks.append(('independent objects '+str(i),len(root.findall('.//p:pic',ns))==len(b['items'])))
        hashes={a['sha256'] for a in data['assets']}
        for name in archive.namelist():
            if name.startswith('ppt/media/') and not name.endswith('/'):
                checks.append(('embedded asset '+name,hashlib.sha256(archive.read(name)).hexdigest() in hashes))
    reader=PdfReader(out/(data['title']+'_板书布局参考.pdf'))
    checks.append(('PDF page count',len(reader.pages)==len(data['layout']['boards'])))
    result={'passed':all(ok for _,ok in checks),'checks':len(checks),'failed':[name for name,ok in checks if not ok],
            'visual_review':'Still requires actual image/PPT inspection; structural checks do not approve appearance.'}
    write_json(destination/'verification.json',result)
    if not result['passed']:raise ValueError(str(result))
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__);sub=parser.add_subparsers(dest='command',required=True)
    build=sub.add_parser('render');build.add_argument('--spec',type=Path,required=True);build.add_argument('--output',type=Path,required=True)
    for name in ('export','verify'):
        command=sub.add_parser(name);command.add_argument('--project',type=Path,required=True)
    args=parser.parse_args()
    if args.command=='render':
        result=render(args.spec,args.output);answer={'assets':len(result['assets']),'boards':len(result['layout']['boards']),'output':str(args.output)}
    elif args.command=='export':answer=export(args.project)
    else:answer=verify(args.project)
    print(json.dumps(answer,ensure_ascii=False))


if __name__=='__main__':main()
